INSERT INTO login.role (id,name) VALUES ('1', 'ADMIN');
INSERT INTO login.role (id,name) VALUES ('2', 'EMP');
INSERT INTO login.role (id,name) VALUES ('3', 'USER');
INSERT INTO login.user_role (user_id, role_id) VALUES ('1', '3');
INSERT INTO login.user_role (user_id, role_id) VALUES ('2', '3');
INSERT INTO login.user_role (user_id, role_id) VALUES ('3', '1');
INSERT INTO login.user_role (user_id, role_id) VALUES ('4', '2');
INSERT INTO login.user_role (user_id, role_id) VALUES ('5', '2');
INSERT INTO login.ciudad (id_ciudad, name) VALUES ('1', 'Cochabamba');
INSERT INTO login.ciudad (id_ciudad, name) VALUES ('2', 'La Paz');
